dataset_config:
  data_root: datasets/Classical
  dataset_name: 11_donors
detector_config:
  embedding_config:
    embedding_name: none
    num_dimensions: 8
    num_features: null
    trainable: true
    variance: 1.0
  flow_config:
    flow_name: glow
    hidden_dim: 32
    num_features: null
    num_flow_layers: 16
    num_mlp_layers: 2
    use_batch_norm: true
    use_channel_wise_splits: true
    use_checkerboard_splits: true
    use_layer_norm: true
optimisation_config:
  batch_size: 32
  lr: 0.001
  min_lr: 1.0e-05
  num_steps: 200
  num_workers: 4
  weight_decay: 0.0
procedure_config:
  experiment_name: null
  gpu_index: 5
  log_frequency: 10
  log_wandb: false
  output_dir: experiments/detector
  plot_histograms: true
  random_seed: 42
  save_metrics: true
  save_model: false
