procedure_config:
  experiment_name: null
  random_seed: 42
  gpu_index: 0
  log_wandb: false
  log_frequency: 10
  output_dir: experiments/final/detector
  save_model: false
  save_metrics: true
  plot_histograms: true
dataset_config:
  data_root: datasets/Classical
  data_type: features
  dataset_name: 10_cover
detector_config:
  embedding_config:
    embedding_name: simple
    num_features: null
    num_dimensions: 8
    variance: 1.0
    trainable: true
  flow_config:
    flow_name: maf
    num_features: null
    hidden_dim: 32
    num_flow_layers: 16
    num_mlp_layers: 2
    use_layer_norm: true
    use_batch_norm: true
    use_channel_wise_splits: true
    use_checkerboard_splits: true
    is_inverse_made: false
optimisation_config:
  lr: 0.001
  min_lr: 1.0e-05
  weight_decay: 0.0
  num_steps: 200
  num_workers: 4
  batch_size: 32
  clip_grad: 1.0
  z_clamp: 10.0
  log_det_clamp: 10.0
  nan_to_num: true
