procedure_config:
  experiment_name: 
  random_seed: 42
  gpu_index: 1
  
  log_wandb: False
  log_frequency: 10
  output_dir: experiments/encoder
  latents_root: datasets/VAELatents

  save_model: False
  save_metrics: False
  plot_histograms: False


dataset_config:
  dataset_name: 45_wine
  data_root: datasets/Classical


encoder_config:
  encoder_type: autoenccoder
  encoder_name: vae
  
  num_encoder_layers: 2
  num_decoder_layers: 2
  
  num_features: 
  hidden_dim: 64
  latent_dim: 8


optimisation_config:
  lr: 0.001
  min_lr: 0.00001
  weight_decay: 0.0

  num_steps: 100
  num_workers: 4
  batch_size: 64
  