dataset_config:
  data_root: datasets/Classical
  dataset_name: 33_skin
encoder_config:
  encoder_name: vae
  encoder_type: autoenccoder
  hidden_dim: 64
  latent_dim: 8
  num_decoder_layers: 2
  num_encoder_layers: 2
  num_features: null
optimisation_config:
  batch_size: 64
  lr: 0.001
  min_lr: 1.0e-05
  num_steps: 100
  num_workers: 4
  weight_decay: 0.0
procedure_config:
  experiment_name: null
  gpu_index: 1
  latents_root: datasets/VAELatents
  log_frequency: 10
  log_wandb: false
  output_dir: experiments/encoder
  plot_histograms: false
  random_seed: 42
  save_metrics: false
  save_model: false
