procedure_config:
  experiment_name:
  random_seed: 42
  gpu_index: 4
  
  log_wandb: True
  log_frequency: 10
  output_dir:

  save_model: False
  save_metrics: True
  plot_histograms: True


dataset_config:
  dataset_name: 4_breastw
  data_root: datasets/Classical


model_config:
  
  embedding_config:
    # embedding_name: none
    embedding_name: periodic
    num_features: 
    num_dimensions: 8

    variance: 1.0
    initialisation: normal
    trainable: True

  flow_config:
    flow_name: real_nvp
    # hidden_dim: 64
    hidden_dim: 256
    num_features:

    num_flow_layers: 16
    num_mlp_layers: 2

    use_channel_wise_splits: True
    use_checkerboard_splits: True

    mlp_activation: relu
    
    use_layer_norm: True
    use_batch_norm: True


optimisation_config:
  lr: 0.001
  min_lr: 0.00001
  weight_decay: 0.0

  num_epochs: 10
  batch_size: 128
  num_workers: 4