procedure_config:

  experiment_name: 
  random_seed: 42
  gpu_index: 0
  
  log_wandb: False
  log_frequency: 10
  output_dir: vae_exp

  save_model: False
  save_metrics: False
  plot_histograms: False
  save_latents_dir: datasets/VAELatents

dataset_config:

  dataset_name: 45_wine
  data_root: datasets/Classical


vae_config:

  num_encoder_layers: 2
  num_decoder_layers: 2
  d_in: 
  d_hidden: 64 
  d_latent: 2

optimisation_config:

  lr: 0.001
  min_lr: 0.00001
  weight_decay: 0.0

  num_steps: 20
  batch_size: 64
  num_workers: 4
  